spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


github:
  api-url: https://api.github.com
  token: ${GITHUB_API_TOKEN}