spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


github:
  api-url: https://api.github.com
  token: ${GITHUB_API_TOKEN}
  authorize-url: https://github.com/login/oauth/authorize
  access-token-url: https://github.com/login/oauth/access_token
  client-id: ${GITHUB_CLIENT_ID}
  client-secret: ${GITHUB_CLIENT_SECRET}

application:
  import-frequency: ${ISSUES_IMPORT_FREQUENCY:60000}
  challenge-frequency: ${ISSUES_CHALLENGE_FREQUENCY:10000}
  challenge-tracking-frequency: ${CHALLENGE_TRACKING_FREQUENCY:10000}
  one-signal:
    app-id: ${ONE_SIGNAL_APP_ID}
    api-auth-key: ${ONE_SIGNAL_API_AUTH_KEY}
    template-id: ${ONE_SIGNAL_TEMPLATE_ID}